### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by mfatrez** [davidvossel/sap_redhat_cluster_connector#2]
Could you test the sap_redhat_cluster_connector with these instances profiles  ?
- PE1_ASCS00_pe1-ascs  
- PE1_D02_pe1-d02  
- PE1_D03_frbsluxv03  
- PE1_D04_frsaruxv03  
- PE1_DVEBMGS01_pe1-d01  
- PE1_ERS11_pe1-aers

Apparently it doesn't work.

Line 268, the result regex not match

**Comment by fdanapfel** [comment]
Hello, please open a support ticket via the Red Hat Customer Portal (https://access.redhat.com) for this issue.

**Comment by mfatrez** [comment]
What is the interest of this repository if you provide this kind of answer?

**Comment by beekhof** [comment]
On the part of the owner?  None I imagine.
You're asking for support from someone that doesn't work on this anymore.

Hence the suggestion to contact Red Hat directly if you want to reliably reach someone that cares,
